---
apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-snmptrapper-config
 namespace: default
data:
  snmptrapper.yml: |
    TrapAddress: prometheus-snmptrapper-debugger:162
    Community:   public
    Retries:     1
    WebhookAddress:  0.0.0.0:9099


    FiringTrap: ".1.3.6.1.4.1.20006.1.7"
    RecoveryTrap: ".1.3.6.1.4.1.20006.1.7"
    Oids:
    # - Name: "oidnSvcEventIndex"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.1"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcHostname"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.2"
    #   Template: "{{.Labels.Severity}}"
    - Name: "oidnSvcHostAlias"
      Oid: ".1.3.6.1.4.1.20006.1.3.1.3"
      Template: "{{.Receiver}}"
    - Name: "oidnSvcHostStateID"
      Oid: ".1.3.6.1.4.1.20006.1.3.1.4"
      Template: '{{ .Labels.instance}}'
    - Name: "oidnSvcHostStateType"
      Oid: ".1.3.6.1.4.1.20006.1.3.1.5"
      Template: "{{.Annotations.description}}"
    - Name: "oidnSvcDesc"
      Oid: ".1.3.6.1.4.1.20006.1.3.1.6"
      Template: '{{.Labels.severity}}'
    # - Name: "oidnSvcStateID"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.7"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcAttempt"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.8"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcDurationSec"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.9"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcGroupName"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.10"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLastCheck"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.11"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLastChange"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.12"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLastOK"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.13"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLastWarn"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.14"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLastCrit"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.15"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLastUnkn"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.16"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcOutput"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.17"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcPerfData"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.18"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcNote"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.19"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcGrapher"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.20"
    #   Template: "{{.Status}}"
    # - Name: "oidnCIIMPACT"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.21"
    #   Template: "{{.Status}}"
    # - Name: "oidnHostClass"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.22"
    #   Template: "{{.Status}}"
    # - Name: "oidnHostCountry"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.23"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcLogConfirmURL"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.25"
    #   Template: "{{.Status}}"
    # - Name: "oidnSvcSource"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.26"
    #   Template: "{{.Status}}"
    # - Name: "oidnAutoTicket"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.27"
    #   Template: "{{.Status}}"
    # - Name: "oidnOTAssignee"
    #   Oid: ".1.3.6.1.4.1.20006.1.3.1.28"
    #   Template: "{{.Status}}"
    
---
# Source: prometheus-snmptrapper/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-snmptrapper
  namespace: default
  labels:
    app: prometheus-snmptrapper
spec:
  type: ClusterIP
  ports:
    - port: 9099
      targetPort: http
      protocol: TCP
  selector:
    app: prometheus-snmptrapper
    release: prometheus-snmptrapper
---
# Source: prometheus-snmptrapper/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-snmptrapper-debugger
  namespace: default
  labels:
    app: prometheus-snmptrapper-debugger
spec:
  type: ClusterIP
  ports:
    - port: 162
      targetPort: snmp-trap
      protocol: UDP
  selector:
    app: prometheus-snmptrapper-debugger
    release: prometheus-snmptrapper-debugger

---
# Source: prometheus-snmptrapper/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prometheus-snmptrapper
  namespace: default
  labels:
    app: prometheus-snmptrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-snmptrapper
      release: prometheus-snmptrapper
  template:
    metadata:
      labels:
        app: prometheus-snmptrapper
        release: prometheus-snmptrapper
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-snmptrapper-config
      containers:
        - name: prometheus-snmptrapper
          image: "sysincz/prometheus_webhook_snmptrapper:latest"
          args:
          - -config /config/snmptrapper.yml -debug
          imagePullPolicy: Always
         
          volumeMounts:
            - name: config-volume
              mountPath: /config
          ports:
          - name: http
            containerPort: 9099
            protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 1m
              memory: 8Mi

---
# Source: prometheus-snmptrapper-debugger/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prometheus-snmptrapper-debugger
  namespace: default
  labels:
    app: prometheus-snmptrapper-debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-snmptrapper-debugger
      release: prometheus-snmptrapper-debugger
  template:
    metadata:
      labels:
        app: prometheus-snmptrapper-debugger
        release: prometheus-snmptrapper-debugger
    spec:
      containers:
        - name: prometheus-snmptrapper-debugger
          image: "sysincz/prometheus_webhook_snmptrapper-debugger:latest"
          imagePullPolicy: Always

          ports:
          - name: snmp-trap
            containerPort: 162
            protocol: UDP
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 1m
              memory: 8Mi